# Generated by Django 5.1 on 2024-08-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('worker', 'Worker')], default='worker', max_length=10),
        ),
    ]
